### ISSUE TITLE
Is customizer still in place (v1.5.7)?

### ISSUE THREAD

**Issue by krisharney** [rafdizzle86/woo-lightspeed-customizer#6]
I searched the current source code, but I do not see the customizer loaded anywhere.  I searched for functions.php and woo-lightspeed-customizer.php within the plugin.  For my immediate testing (local), I placed a call in the plug-in initialization module.  I would not prefer to edit the core source in the event my client upgrades.

Am I missing something?

Also, is there a filter or hook you would suggest calling AFTER the woocommerce item is created during the import?  I noticed wclsi_import_ls_result_single_prod is called prior.  The reason I am investigating this is my client wishes to make use of the custom fields in the lightspeed product.

Thanks,

-Kris

**Comment by rafiyagi** [comment]
Hi @krisharney - the woo-customizer is not part of the Woo-Lightspeed plugin. It is meant more to help guide developers on how to hook into the various actions and filters the plugin provides.

As far as a hook after the woocommerce item is created - you could look into the WooCommerce Hook API and see if you can find something there: https://docs.woocommerce.com/wc-apidocs/hook-docs.html. Otherwise I know the WordPress has the `wp_insert_post` hook that is triggered after a post is saved: https://codex.wordpress.org/Plugin_API/Action_Reference/wp_insert_post

**Comment by krisharney** [comment]
Thank you.

I have since provided a solution for my client.
Best regards,

-Kris

**Comment by krisharney** [comment]
One thing I would ask is that when the client updates, you don't obliterate
the hook file.  The last time he updated the software, we had to redeploy
the customizer php file.  That was a shock to him ;). Fortunately, I had it
in source control, so it wasn't a big deal to me.  But if, in the future, I
am not around, I am not certain he'd know what to do.

**Comment by krisharney** [comment]
Thank you.  This question was raised a while back.  Since that time, I've
provided a solution to my client's case.
